# Generated by Django 6.0 on 2025-12-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis korzyści'),
        ),
    ]
