# Generated by Django 6.0 on 2025-12-28 20:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.validate_pesel], verbose_name='PESEL'),
        ),
    ]
