# Generated by Django 6.0 on 2025-12-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_pesel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'verbose_name': 'Zapis', 'verbose_name_plural': 'Zapisy'},
        ),
        migrations.RenameField(
            model_name='classsessions',
            old_name='uczestnicy',
            new_name='participants',
        ),
    ]
