# Generated by Django 6.0 on 2025-12-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_enrollments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsessions',
            name='date',
            field=models.DateTimeField(verbose_name='Data zajęć'),
        ),
    ]
