# Generated by Django 6.0 on 2026-01-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_classsessions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='entries_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Zostaw puste dla karnetu bez limitu (Open)', null=True, verbose_name='Limit wejść w tygodniu'),
        ),
    ]
